### ISSUE TITLE
What is the meaning of the prefix 4x..

### ISSUE THREAD

**Issue by ryebreadsalad** [industrial-edge/modbus-tcp-connector-getting-started#1]
What is the meaning of the address with the 4x as prefix (4x400001) in the screenshot of this tutorial.

0x0.. is hexadecimal number
0b0... is a binary number
4x0.. is what kind of number?

Please clarify, none of my colleages know.

**Comment by vladEdge** [comment]
This is notation specific for Modbus registers. Register types and reference ranges recognized with Modicon notation are as follows:
0x = Coil = 000001-065535
1x = Discrete Input = 100001-165535
3x = Input Register = 300001-365535
4x = Holding Register = 400001-465535
